# Generated by Django 4.2.8 on 2024-06-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladvisorapp', '0002_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
