# Generated by Django 4.2.8 on 2024-06-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladvisorapp', '0004_review_hotelimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.CharField(max_length=200),
        ),
    ]
