# Generated by Django 4.2.8 on 2024-06-07 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladvisorapp', '0006_rename_rating_hotel_average_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='average_rating',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 7, 16, 11, 14, 663928, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to='hotels/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
